var pc,channel,index=0,progress=document.getElementsByTagName("progress")[0],span=document.getElementsByTagName("span")[0],firefox=void 0!=window.mozRTCPeerConnection;setup();
function setup(){pc=new (window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection)({iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun.services.mozilla.com"}]});pc.onicecandidate=function(a){pc.localDescription&&prepareEmail()};if(""==location.search){var a=document.getElementsByTagName("input")[0];span.textContent="or drag and drop";a.style.display="inline";document.ondragover=function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect=
"copy"};document.ondragenter=document.ondragover;document.ondrop=function(b){b.stopPropagation();b.preventDefault();b=b.dataTransfer.files[0];span.textContent=b.name+" ";a.style.display="none";createChannel(b)};a.onchange=function(){span.textContent="";createChannel(this.files[0])}}else pc.ondatachannel=function(a){console.log("Connected");var c=document.getElementsByTagName("a")[0];c.style.display="none";channel=a.channel;a=channel.label;var d=a.substr(a.indexOf(" ")+1);c.download=d;c.textContent=
"Save "+d;span.textContent="Receiving "+d;if(firefox&&0<pc.remoteDescription.sdp.indexOf("mozilla"))channel.onmessage=function(a){span.textContent="";c.style.display="inline";c.href=window.URL.createObjectURL(a.data)};else{channel.binaryType="arraybuffer";var e=new Uint8Array(parseInt(a.substring(0,a.indexOf(" "))),10);progress.max=e.length;progress.style.display="inline";index=0;channel.onmessage=function(a){a=new Uint8Array(a.data);e.set(a,index);progress.value=index;index+=a.length;index==e.length&&
(span.textContent="",progress.style.display="none",c.style.display="inline",c.href=window.URL.createObjectURL(new Blob([e])))}}},processPeerData(location.search.substr(1))}
function createChannel(a){channel=pc.createDataChannel(a.size+" "+a.name);pc.createOffer(onDescCreated,onCreateOfferError);channel.onopen=function(){document.getElementsByTagName("a")[0].style.display="none";span.textContent+="sending";if(firefox&&0<pc.remoteDescription.sdp.indexOf("mozilla"))channel.send(a);else{channel.binaryType="arraybuffer";var b=new FileReader;b.onload=function(){progress.style.display="inline";progress.max=this.result.byteLength;sendChunk(this.result,0)};b.readAsArrayBuffer(a)}}}
function sendChunk(a,b){channel.send(a.slice(b,b+=16384));b<a.byteLength?(progress.value=b,setTimeout(sendChunk,50,a,b)):(progress.style.display="none",span.textContent=span.textContent.slice(0,-4)+"t")}function onCreateOfferError(a){logError("Error creating offer: "+JSON.stringify(a))}function onDescCreated(a){pc.setLocalDescription(a,onLocalDescSuccess,onLocalDescError)}function onLocalDescSuccess(){console.log("Local sdp created: "+JSON.stringify(pc.localDescription));prepareEmail()}
function onLocalDescError(a){logError("Local description could not be created: "+JSON.stringify(a))}
function prepareEmail(){var a=document.getElementsByTagName("a")[0];if("complete"==pc.iceGatheringState&&""==a.textContent){var b=pc.localDescription.sdp;console.log("Sdp to email: "+JSON.stringify(b));var c=Array(8);c[0]=strBetween("o=","\r\n").replace(/ /g,"+");c[1]=strBetween("m=application ","\r\n").replace(/ /g,"+").replace(/\//g,"_");c[2]=strBetween("c=IN IP4 ","\r");var d=b.indexOf(firefox?"\r\na=sendrecv":"\r\na=ice-ufrag:",index);c[3]=b.substring(index-1,d).replace(/\r\na=candidate:/g,"_").replace(/ generation 0/g,
"").replace(/ /g,"+");index=d;c[4]=strBetween("a=ice-ufrag:","\r\n").replace(/\//g,".").replace(/;/g,"_");index=d;c[5]=strBetween("a=ice-pwd:","\r\n").replace(/\//g,".").replace(/;/g,"_");firefox&&(index=0);c[6]=strBetween("a=fingerprint:sha-256 ","\r\n").replace(/:/g,"");c[7]=strBetween("a=sctpmap:","\r\n").replace(/ /g,"+");b=c.join("~");console.log("Email query string: "+b);""==location.search?(a.textContent="Send email offering data transfer",a.href="mailto:?subject=File transfer offer&body=Please click the link below to receive the file.%0D%0A%0D%0Awww.silvawood.co.uk/p2pData/?"+
b,a.onclick="window.open("+a.href+", 'mail'); event.preventDefault()",window.addEventListener("storage",function(a){processPeerData(a.newValue);localStorage.clear()})):(a.textContent="Send email accepting data transfer",a.href="mailto:?subject=File transfer acceptance&body=Please click the link below to send the file.%0D%0A%0D%0Awww.silvawood.co.uk/p2pData/answer.htm?"+b);console.log("Length: "+a.href.length)}}
function strBetween(a,b){var c=pc.localDescription.sdp,d=c.indexOf(a,index);if(0>d)return"";var d=d+a.length,e=c.indexOf(b,d);index=e+b.length;return c.substring(d,e)}
function processPeerData(a){console.log("Processing peer data");var b=window.RTCSessionDescription||window.mozRTCSessionDescription||window.webkitRTCSessionDescription;a=a.split("~");b=new b;b.sdp="v=0\r\no="+a[0].replace(/\+/g," ")+"\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS\r\nm=application "+a[1].replace(/_/,"/").replace(/\+/g," ")+"\r\nc=IN IP4 "+a[2]+a[3].replace(/_/g,"\r\na=candidate:").replace(/\+/g," ")+"\r\na=end-of-candidates\r\na=ice-ufrag:"+a[4].replace(/\./g,"/").replace(/_/g,";")+"\r\na=ice-pwd:"+
a[5].replace(/\./g,"/").replace(/_/g,";")+"\r\na=fingerprint:sha-256 "+a[6].replace(/(.{2})/g,"$1:").slice(0,-1)+"\r\na=setup:"+(""==location.search?"active":"actpass")+"\r\na=mid:"+(firefox?"sdparta_0":"data")+"\r\na=sctpmap:"+a[7].replace(/\+/g," ")+"\r\n";b.type=""==location.search?"answer":"offer";console.log("sdp string:"+b.sdp);pc.setRemoteDescription(b,onRemoteDescSuccess,onRemoteDescError)}
function onRemoteDescSuccess(){console.log("Remote sdp successfully set");"offer"==pc.remoteDescription.type?pc.createAnswer(onDescCreated,onCreateAnswerError):console.log("Connected")}function onRemoteDescError(a){logError("Remote sdp could not be set: "+(a.message?a.message:a))}function onCreateAnswerError(a){logError("Error creating answer: "+(a.message?a.message:a))}function logError(a){console.log(a)};